package org.oregami.service;

public enum ServiceErrorMessage {

	TASK_TASKNAME_EMPTY,
	TASK_TASKNAME_TOO_SHORT,
	TASK_DESCRIPTION_EMPTY,
	TASK_FINISHED_EMPTY,

    SUBTASK_DESCRIPTION_EMPTY,
    SUBTASK_DESCRIPTION_TOO_SHORT,

    LANGUAGE_NAME_EMPTY,
    LANGUAGE_NAME_TOO_SHORT,
    LANGUAGE_DESCRIPTION_EMPTY,
    LANGUAGE_DESCRIPTION_TOO_SHORT
	
}
